version: '3'

services:
  frontend:
    image: harish492/frontend-image:latest
    ports:
      - "85:85"
    networks:
      - my-network

  backend:
    image: harish492/backend-image:latest
    ports:
      - "3001:3001"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
