# # Use the latest 2.1 version of CircleCI pipeline process engine.
# # See: https://circleci.com/docs/configuration-reference

version: 2.1

jobs:
  frontend-tests:
    machine:
      image: ubuntu-2204:2022.07.1

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
          working_directory: Frontend/AcademicTool/components
      - run:
          name: Run Tests
          command: npm test
          working_directory: Frontend/AcademicTool/components

      - run:
          name: "Build Frontend Docker Image"
          command: |
            ## PERSONALIZATION: Update username to your Docker username or CircleCI environment variable.
            docker build -t harish492/docker_assignment:AA_FE_latest -f Frontend/AcademicTool/Dockerfile .
      - run:
          name: "Save Frontend Image"
          command: |
            ## PERSONALIZATION: Update username to your Docker username or CircleCI environment variable.
            docker save -o frontend-image.tar harish492/docker_assignment:AA_FE_latest
      - run:
          name: "login frontend"
          command: |
            ## PERSONALIZATION: Update username to your Docker username or CircleCI environment variable.
            echo $DOCKERHUB_PASS | docker login -u harish492 --password-stdin
            docker push harish492/docker_assignment:AA_FE_latest

  backend-tests:
    machine:
      image: ubuntu-2204:2022.07.1

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
          working_directory: Backend/backendAcademic
      - run:
          name: Run Tests
          command: npm test 
          working_directory: Backend/backendAcademic

      - run:
          name: "Build Backend Docker Image"
          command: |
            ## PERSONALIZATION: Update username to your Docker username or CircleCI environment variable.
            docker build -t harish492/docker_assignment:AA_BE_latest -f Backend/backendAcademic/Dockerfile .
      - run:
          name: "Save Backend Image"
          command: |
            ## PERSONALIZATION: Update username to your Docker username or CircleCI environment variable.
            docker save -o backend-image.tar harish492/docker_assignment:AA_BE_latest
      - run:
          name: "Load and Push Backend Image"
          command: |
            ## PERSONALIZATION: Update username to your Docker username or CircleCI environment variable.
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push harish492/docker_assignment:AA_BE_latest
      - run:
          name: "compose Image8"
          command: |
             docker compose push


workflows:
  Setup_and_Test:
    jobs:
      - frontend-tests
      - backend-tests